---
- name: Test Local
  hosts: 10.33.33.49
  vars:
          ansible_become_pass: 123Security!@#
  tasks:
        - name: Test SSH
          ansible.builtin.shell:
                 cmd: hostnamectl
                 
        - name: Ping 8.8.8.8
          ansible.builtin.shell:
            cmd: ping -c 2 8.8.8.8
            
        - name: Test Execute Script
          ansible.builtin.script: /home/agioadmin/ansible_poc_config/default_config_linux.sh
          become: yes
          become_method: sudo
